export const menArray = [
  {
    blockname: 'images',
    mainImgSrc: '/images/image-product-1.jpg',
    smallMenArray: {
      src1: '/images/image-product-1-thumbnail.jpg',
      src2: '/images/image-product-2-thumbnail.jpg',
      src3: '/images/image-product-3-thumbnail.jpg',
      src4: '/images/image-product-4-thumbnail.jpg',
    },
    textClass: 'para-one',
    companyName: 'Fall brands',
    itemTitle: 'fall limited edition sneakers',
    description:
      'These low-sneakers are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 125,
    rate: 50,
    oldPrice: 250,
  },
  {
    blockname: 'image-one',
    mainImgSrc: '/other images/men/brand-men/brand-men-one.jpg',
    smallMenArray: {
      src1: '/other images/men/brand-men/brand-men-one_176x176.jpg',
      src2: '/other images/men/brand-men/brand-men-two_176x176.jpg',
      src3: '/other images/men/brand-men/brand-men-three_176x176.jpg',
      src4: '/other images/men/brand-men/brand-men-four_176x176.jpg',
    },
    textClass: 'para-two',
    companyName: 'ZARA brands',
    itemTitle: 'zara sneakers 2022',
    description:
      'These ZARA new sneakers are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 155,
    rate: 20,
    oldPrice: 120,
  },
  {
    blockname: 'image-two',
    mainImgSrc: '/other images/men/jordan/jordan-one.jpg',
    smallMenArray: {
      src1: '/other images/men/jordan/jordan-one_176x176.jpg',
      src2: '/other images/men/jordan/jordan-two_176x176.jpg',
      src3: '/other images/men/jordan/jordan-three_176x176.jpg',
      src4: '/other images/men/jordan/jordan-four_176x176.jpg',
    },
    textClass: 'para-three',
    companyName: 'Jordan X',
    itemTitle: 'Jordan new 2021 brand',
    description:
      'These Jordan x shoes are your perfect sport and casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 625,
    rate: 52,
    oldPrice: 1225,
  },
  {
    blockname: 'image-three',
    mainImgSrc: '/other images/men/men-shoe/men-shoe-one.jpg',
    smallMenArray: {
      src1: '/other images/men/men-shoe/men-shoe-one_176x176.jpg',
      src2: '/other images/men/men-shoe/men-shoe-two_176x176.jpg',
      src3: '/other images/men/men-shoe/men-shoe-three_176x176.jpg',
      src4: '/other images/men/men-shoe/men-shoe-four_176x176.jpg',
    },
    textClass: 'para-four',
    companyName: 'Anbessa shoe LTD',
    itemTitle: 'Brand Ethiopian Anbessa shoe ',
    description:
      'These Anbessa leather shoe are your perfect weadding and meeting wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 650,
    rate: 40,
    oldPrice: 1455.55,
  },
  {
    blockname: 'image-four',
    mainImgSrc: '/other images/men/men-type/men-type-one.jpg',
    smallMenArray: {
      src1: '/other images/men/men-type/men-type-one_176x176.jpg',
      src2: '/other images/men/men-type/men-type-two_1_176x176.jpg',
      src3: '/other images/men/men-type/men-type-three_1_176x176.jpg',
      src4: '/other images/men/men-type/men-type-one_176x176.jpg',
    },
    textClass: 'para-five',
    companyName: 'Gucci PLC',
    itemTitle: 'Gucci new youth shoes',
    description:
      'These Gucci shoes are your perfect casual and classic party  wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 399.99,
    rate: 10,
    oldPrice: 455,
  },
  {
    blockname: 'image-five',
    mainImgSrc: '/other images/men/nike-new/nike-new-one.jpg',
    smallMenArray: {
      src1: '/other images/men/nike-new/nike-new-one_176x176.jpg',
      src2: '/other images/men/nike-new/nike-new-two_176x176.jpg',
      src3: '/other images/men/nike-new/nike-new-three_176x176.jpg',
      src4: '/other images/men/nike-new/nike-new-four_176x176.jpg',
    },
    textClass: 'para-six',
    companyName: 'Nike AIR  ',
    itemTitle: 'Nike AIR Jordan 2021',
    description:
      'These Nike Air are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 225,
    rate: 16,
    oldPrice: 325,
  },
  {
    blockname: 'image-six',
    mainImgSrc: '/other images/men/nike-pic/nike-pic-one.jpg',
    smallMenArray: {
      src1: '/other images/men/nike-pic/nike-pic-one_176x176.jpg',
      src2: '/other images/men/nike-pic/nike-pic-two_176x176.jpg',
      src3: '/other images/men/nike-pic/nike-pic-three_176x176.jpg',
      src4: '/other images/men/nike-pic/nike-pic-four_176x176.jpg',
    },
    textClass: 'para-seven',
    companyName: 'Nike',
    itemTitle: 'Nike brand sport shoe',
    description:
      'These Nike brand sport shoe are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 165,
    rate: 45,
    oldPrice: 250,
  },
  {
    blockname: 'image-seven',
    mainImgSrc: '/other images/men/turk/turk-shoe-one.jpg',
    smallMenArray: {
      src1: '/other images/men/turk/turk-shoe-one_2_176x176.jpg',
      src2: '/other images/men/turk/turk-shoe-two_176x176.jpg',
      src3: '/other images/men/turk/turk-shoe-three_1_176x176.jpg',
      src4: '/other images/men/turk/turk-shoe-four_176x176.jpg',
    },
    textClass: 'para-eight',
    companyName: 'Turkey fashion LTD',
    itemTitle: 'Turkey D square sport shoe',
    description:
      'These Turkey flat brand sport shoe brand sport shoe are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 295,
    rate: 35,
    oldPrice: 350,
  },
];

export const womenArray = [
  {
    blockname: 'images-girl',
    mainImgSrc: '/other images/women/girl-brand/girl-brand-one.jpg',
    smallMenArray: {
      src1: '/other images/women/girl-brand/girl-brand-one_176x176.jpg',
      src2: '/other images/women/girl-brand/girl-brand-two_176x176.jpg',
      src3: '/other images/women/girl-brand/girl-brand-three_176x176.jpg',
      src4: '/other images/women/girl-brand/girl-brand-four_176x176.jpg',
    },
    textClass: 'para-girl-one',
    companyName: 'ZUZZA PLC',
    itemTitle: 'ZUZZA 2022 Girls shoe  outdoor',
    description:
      'These ZUZZA 2022 Girls shoe  outdoor are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 225,
    rate: 15,
    oldPrice: 195.99,
  },
  {
    blockname: 'images-girl-one',
    mainImgSrc: '/other images/women/girl-brand-two/girl-brand-main.jpg',
    smallMenArray: {
      src1: '/other images/women/girl-brand-two/girl-new-one_176x176.jpg',
      src2: '/other images/women/girl-brand-two/girl-new-two_176x176.jpg',
      src3: '/other images/women/girl-brand-two/girl-new-three_176x176.jpg',
      src4: '/other images/women/girl-brand-two/girl-new-four_176x176.jpg',
    },
    textClass: 'para-girl-two',
    companyName: 'Dura shoes LTD',
    itemTitle: 'Dura 2022 Girls shoe  outdoor',
    description:
      'These Dura 2022 Girls shoe outdoor are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 149,
    rate: 35,
    oldPrice: 200.99,
  },
  {
    blockname: 'images-girl-two',
    mainImgSrc: '/other images/women/girl-hill/girl-hill-main.jpg',
    smallMenArray: {
      src1: '/other images/women/girl-hill/girl-hill-one_176x176.jpg',
      src2: '/other images/women/girl-hill/girl-hill-two_176x176.jpg',
      src3: '/other images/women/girl-hill/girl-hill-three_176x176.jpg',
      src4: '/other images/women/girl-hill/girl-hill-four_176x176.jpg',
    },
    textClass: 'para-girl-three',
    companyName: 'Holluka brands LTD',
    itemTitle: 'Holluka Girls hill shoe',
    description:
      'These Holluka Girls 2022 Girls shoe  outdoor are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 410,
    rate: 35,
    oldPrice: 198.99,
  },
  {
    blockname: 'images-girl-three',
    mainImgSrc: '/other images/women/girl-shoe/girl-shoe-one.jpg',
    smallMenArray: {
      src1: '/other images/women/girl-shoe/girl-shoe-one_176x176.jpg',
      src2: '/other images/women/girl-shoe/girl-shoe-two_176x176.jpg',
      src3: '/other images/women/girl-shoe/girl-shoe-three_176x176.jpg',
      src4: '/other images/women/girl-shoe/girl-shoe-four_176x176.jpg',
    },
    textClass: 'para-girl-four',
    companyName: 'Azul LTD',
    itemTitle: 'classic-girl-sandle',
    description:
      'These Holluka Girls 2022 Girls shoe  outdoor are your perfect casual wear companion.Featuring a durable rubber outer sole. theyll withstand everything the weather can  offer.',
    newOffer: 110,
    rate: 35,
    oldPrice: 98.99,
  },
];
